# Name of this GitHub Actions workflow.
name: Trigger Doc Update

# Only trigger when the release workflow has succeeded
on:
  workflow_run:
    workflows: ["release"]
    types: [completed]

jobs:
  trigger-doc-update:
    name: Trigger Doc Update
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.SEMGREP_DOCS_BOT_APP_ID }}
          private_key: ${{ secrets.SEMGREP_DOCS_BOT_PRIVATE_KEY }}
          repositories: >-
             ["sinat101/mockdocs"]
      - name: Trigger doc update workflow
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          curl --location \
          --request POST \
          --header "Accept: application/vnd.github+json" \
          --header "Authorization: Bearer $GITHUB_TOKEN" \
          https://api.github.com/repos/sinat101/mockdocs/dispatches \
          --data '{"event_type":"new_release"}'
